// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA5YbxNgNo0-qUwfNCeIBRxxt1CqYOti0',
    appId: '1:723043734264:android:d54ff1eaed235ac68a610d',
    messagingSenderId: '723043734264',
    projectId: 'para-el-farabi',
    storageBucket: 'para-el-farabi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz2Pcu84dQlIT0nTKIucdXXyC8xslIOlU',
    appId: '1:723043734264:ios:18733dfee49adae98a610d',
    messagingSenderId: '723043734264',
    projectId: 'para-el-farabi',
    storageBucket: 'para-el-farabi.appspot.com',
    iosBundleId: 'com.example.flutterFarabiApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnLO6BYxYQwZX-fDLViTr_WOTA5B9Ad-4',
    appId: '1:723043734264:web:616747626aca7d338a610d',
    messagingSenderId: '723043734264',
    projectId: 'para-el-farabi',
    authDomain: 'para-el-farabi.firebaseapp.com',
    storageBucket: 'para-el-farabi.appspot.com',
    measurementId: 'G-9SG3FVD8JK',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz2Pcu84dQlIT0nTKIucdXXyC8xslIOlU',
    appId: '1:723043734264:ios:18733dfee49adae98a610d',
    messagingSenderId: '723043734264',
    projectId: 'para-el-farabi',
    storageBucket: 'para-el-farabi.appspot.com',
    iosBundleId: 'com.example.flutterFarabiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnLO6BYxYQwZX-fDLViTr_WOTA5B9Ad-4',
    appId: '1:723043734264:web:4112cece9d8481d68a610d',
    messagingSenderId: '723043734264',
    projectId: 'para-el-farabi',
    authDomain: 'para-el-farabi.firebaseapp.com',
    storageBucket: 'para-el-farabi.appspot.com',
    measurementId: 'G-BLS7S1FC6G',
  );

}